{% set version = "2.0.0" %}
{% set sha256 = "7521d41848234da41b50cfad5c9a3024d4cfc5a1454c9b6df52ed07266fb07be" %}

package:
  name: interpolation
  version: {{ version }}

source:
  fn: interpolation.py-{{ version }}.tar.gz
  url: https://github.com/EconForge/interpolation.py/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - pip
    - python>=3.6
    - setuptools
  run:
    - python>=3.6
    - numba
    - numpy
    - pandas
    - tempita
    - scipy

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD 2-Clause
  summary: 'Interpolation in Python'

extra:
  recipe-maintainers:
    - albop
