{% set version = "2.1.4" %}

package:
  name: interpolation
  version: {{ version }}

source:
  git_url: https://github.com/EconForge/interpolation.py.git
  git_rev: v{{ version }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - poetry
  run:
    - python >=3.6
    - numba >=0.49
    - numpy
    - pandas
    - tempita
    - scipy

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: COPYING
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
