{% set name = "interpolation" %}
{% set version = "2.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/EconForge/interpolation.py/archive/v{{ version }}.tar.gz
  sha256: 637aca4c60e862b2d2367b091a179f48d372a6c4277f4eb51856dc58ec93a6dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<=3.12
    - poetry >=1.2
  run:
    - python >=3.8,<=3.12
    - numba >=0.57
    - scipy >=1.10

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
    - jan-janssen
