{% set name = "interpolation" %}
{% set version = "2.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9fce6be72229e3d10ddceaa1d964bda20a37df5107dcbe04adb03fc34ebfb14f

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - pip ==20.0.2
    - python >=3.6
    - poetry
  run:
    - python >=3.6
    - numba >=0.49
    - numpy
    - tempita
    - scipy

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
