{% set name = "interpolation" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d480af050c14d6589b89c4773ad4cf9f4bcb4c1138b895e62e10fea7c01043b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip ==20.0.2
    - python >=3.6
    - poetry
  run:
    - python >=3.6
    - numba >=0.47
    - numpy
    - tempita
    - scipy

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
