{% set version = "2.1.0" %}
{% set sha256 = "435c5e0fb8ed356fe8ca5b528b5e49e1e4d2f630230f096e9a738122076a8765" %}

package:
  name: interpolation
  version: {{ version }}

source:
  fn: interpolation.py-{{ version }}.tar.gz
  url: https://github.com/EconForge/interpolation.py/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - pip
    - python>=3.6
    - setuptools
  run:
    - python>=3.6
    - numba
    - numpy
    - pandas
    - tempita
    - scipy

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD 2-Clause
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
