{% set name = "interpolation" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 637aca4c60e862b2d2367b091a179f48d372a6c4277f4eb51856dc58ec93a6dc
  patches:
    - fix_poetry.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip ==22.2.2
    - python >=3.8,<3.11
    - poetry
  run:
    - python >=3.8,<3.11
    - numba >=0.47
    - numpy >=1.22.2
    - tempita >=0.5.2
    - scipy >=1.4.1
    - packaging >=21.3

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
