travis:
  secure:
    BINSTAR_TOKEN: VDy1AAhA6qkxVx948GfUMKN70ZODIpkom6LfyY57bh/PPNiWO646+AySZ3A48VmmlhJ2NMwactbsCyyuUpOK124FcL77M2SnQP7yLbQDKBZ9ka15cn+4Zw3cjXQdXGYn6ga6dzdEsUpsU6fYH0bFZkaJWprGO2YZB7hxCux+798Zd9L+mz1veAjwtqG4NABpWIpwdCw4qtuz5ha2FEXSA2iZgpHpIlej1TLKcb2loJm18GE6bM5osVYSv7zi6JLEocHMUER6Rme1lRpeYm64e9FZ6QIpI7KIsy4wjtqkQIrl7pCKf3IOt71VTdJ9eLJBnfeSaST7VfcmjxwQExfi/+mhXY3ky8PL9hl+jbUDan71fQQ7boP6Hp7E02f4ME+oTVmepzIgM9BNO5+we/FcrzWoH0GqD7OSIwHhjZqMz9etbnJVYB1ptXia/RbhSq4H0J1HvfbPWn+IiUIGmGQ4JKP6hbxGis2tEd2bRzZ2RS7vRUALqy7MQFrDlyqFKOpKLJ1OHt3kKazkzfpj4tFrJtXhFlvLVtHBUUY+Rs0g+UFV3AV2z0AoZwteiKOBTrozCtrlu86cmlWC+vSfFMZe0O9LXIyUWjsgZ4dnZoPp5u0JceJD9St8+v/skATdIje8T9YJXjzh8/gQLvtI/k+BzN/k4WCDWPN5Ohhq79rWv+A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
